version: '2.0'
services:
  vsf-app:
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    environment:
      VS_ENV: ${VS_ENV}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VSF_API_DOMAIN: ${VSF_API_DOMAIN}
      DEFAULT_STORE_ES_INDEX: ${DEFAULT_STORE_ES_INDEX}
    volumes:
      - './babel.config.js:/var/www/babel.config.js'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './tsconfig-build.json:/var/www/tsconfig-build.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
      - './packages:/var/www/packages'
    tmpfs:
      - /var/www/dist
    networks:
      - default
      - reverseproxy
      - vue-storefront-api
    ports:
      - '3000:3000'

networks:
  reverseproxy:
    external:
      name: webdevelopmentreverseproxy_default
  vue-storefront-api:
    external:
      name: vue-storefront-api_default
