export const SN_BUDSIES = 'budsies';
export const CUSTOMER_EMAIL_SET = SN_BUDSIES + '/CUSTOMER_EMAIL_SET';
export const CUSTOMER_TYPES_SET = SN_BUDSIES + '/CUSTOMER_TYPES_SET';
export const HOSPITALS_SET = SN_BUDSIES + '/HOSPITALS_SET';
export const STORE_RATING_SET = SN_BUDSIES + '/STORE_RATING_SET';
