export const LAST_USED_CUSTOMER_EMAIL = 'LAST_USED_CUSTOMER_EMAIL';
export const LAST_USED_CUSTOMER_FIRST_NAME = 'LAST_USED_CUSTOMER_FIRST_NAME';
export const LAST_USED_CUSTOMER_LAST_NAME = 'LAST_USED_CUSTOMER_LAST_NAME';
export const LAST_USED_CUSTOMER_PHONE_NUMBER = 'LAST_USED_CUSTOMER_PHONE_NUMBER';
export const LAST_USED_CUSTOMER_SHIPPING_COUNTRY = 'LAST_USED_CUSTOMER_SHIPPING_COUNTRY';
