import { SN_PERSISTED_CUSTOMER_DATA } from './store-name';

export const LAST_USED_CUSTOMER_EMAIL = SN_PERSISTED_CUSTOMER_DATA + '/LAST_USED_CUSTOMER_EMAIL';
export const LAST_USED_CUSTOMER_FIRST_NAME = SN_PERSISTED_CUSTOMER_DATA + '/LAST_USED_CUSTOMER_FIRST_NAME';
export const LAST_USED_CUSTOMER_LAST_NAME = SN_PERSISTED_CUSTOMER_DATA + '/LAST_USED_CUSTOMER_LAST_NAME';
export const LAST_USED_CUSTOMER_PHONE_NUMBER = SN_PERSISTED_CUSTOMER_DATA + '/LAST_USED_CUSTOMER_PHONE_NUMBER';
export const LAST_USED_CUSTOMER_SHIPPING_COUNTRY = SN_PERSISTED_CUSTOMER_DATA + '/LAST_USED_CUSTOMER_SHIPPING_COUNTRY';
