export enum ProductId {
  FOREVERS_DOG = 73,
  FOREVERS_CAT = 74,
  FOREVERS_OTHER = 75,
  BULK_PLUSH_SAMPLE = 139,
  BULK_PILLOW_SAMPLE = 259,
  BULK_KEYCHAIN_SAMPLE = 507,
  GOLF_COVERS_DOG = 571,
  GOLF_COVERS_CAT = 573,
  GOLF_COVERS_OTHER = 575,
}
