import { SN_RAFFLE } from './store-name';

export const FETCH_CURRENT_STATE = SN_RAFFLE + '/FETCH_CURRENT_STATE';
export const REGISTER = SN_RAFFLE + '/REGISTER';
export const FETCH_WINNING_TICKETS = SN_RAFFLE + '/FETCH_WINNING_TICKETS';
export const VERIFY_TOKEN = SN_RAFFLE + '/VERIFY_TOKEN';
export const SYNCHRONIZE = SN_RAFFLE + '/SYNCHRONIZE';
