import { SN_RAFFLE } from './store-name';

export const GET_PARTICIPANT_DATA = SN_RAFFLE + '/GET_PARTICIPANT_DATA';
export const GET_CURRENT_STATE = SN_RAFFLE + '/GET_CURRENT_STATE';
export const GET_LAST_WINNING_TICKETS = SN_RAFFLE + '/GET_LAST_WINNING_TICKETS';
export const GET_REFERRER_TOKEN = SN_RAFFLE + '/GET_REFERRER_TOKEN';
export const GET_IS_SYNCED = SN_RAFFLE + '/GET_IS_SYNCED';
