import { SN_RAFFLE } from './store-name';

export const PARTICIPANT_DATA_SET = SN_RAFFLE + '/PARTICIPANT_DATA_SET';
export const CURRENT_STATE_SET = SN_RAFFLE + '/CURRENT_STATE_SET';
export const LAST_WINNING_TICKETS_SET = SN_RAFFLE + '/LAST_WINNING_TICKETS_SET';
export const REFERRER_TOKEN_SET = SN_RAFFLE + '/REFERRER_TOKEN_SET';
export const IS_SYNCED_SET = SN_RAFFLE + '/IS_SYNCED_SET';
