import { SN_INSPIRATION_MACHINE } from './store-name';

export const FETCH_EXTRAS = SN_INSPIRATION_MACHINE + '/FETCH_EXTRAS';
export const FETCH_THEMES = SN_INSPIRATION_MACHINE + '/FETCH_THEMES';
export const REQUEST_KIT = SN_INSPIRATION_MACHINE + '/REQUEST_KIT';
